# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projekte/Arty/hw/hw.srcs/sources_1/ip/Sub/Sub.xci
# IP: The module: 'Sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/Sub/Sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sub'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Projekte/Arty/hw/hw.srcs/sources_1/ip/Sub/Sub.xci
# IP: The module: 'Sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/Sub/Sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
