create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {cntr_100MHZ[0]} {cntr_100MHZ[1]} {cntr_100MHZ[2]} {cntr_100MHZ[3]} {cntr_100MHZ[4]} {cntr_100MHZ[5]} {cntr_100MHZ[6]} {cntr_100MHZ[7]} {cntr_100MHZ[8]} {cntr_100MHZ[9]} {cntr_100MHZ[10]} {cntr_100MHZ[11]} {cntr_100MHZ[12]} {cntr_100MHZ[13]} {cntr_100MHZ[14]} {cntr_100MHZ[15]} {cntr_100MHZ[16]} {cntr_100MHZ[17]} {cntr_100MHZ[18]} {cntr_100MHZ[19]} {cntr_100MHZ[20]} {cntr_100MHZ[21]} {cntr_100MHZ[22]} {cntr_100MHZ[23]} {cntr_100MHZ[24]} {cntr_100MHZ[25]} {cntr_100MHZ[26]} {cntr_100MHZ[27]} {cntr_100MHZ[28]} {cntr_100MHZ[29]} {cntr_100MHZ[30]} {cntr_100MHZ[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {alu_read_data[0]} {alu_read_data[1]} {alu_read_data[2]} {alu_read_data[3]} {alu_read_data[4]} {alu_read_data[5]} {alu_read_data[6]} {alu_read_data[7]} {alu_read_data[8]} {alu_read_data[9]} {alu_read_data[10]} {alu_read_data[11]} {alu_read_data[12]} {alu_read_data[13]} {alu_read_data[14]} {alu_read_data[15]} {alu_read_data[16]} {alu_read_data[17]} {alu_read_data[18]} {alu_read_data[19]} {alu_read_data[20]} {alu_read_data[21]} {alu_read_data[22]} {alu_read_data[23]} {alu_read_data[24]} {alu_read_data[25]} {alu_read_data[26]} {alu_read_data[27]} {alu_read_data[28]} {alu_read_data[29]} {alu_read_data[30]} {alu_read_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list alu_read_dv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list ctrl_logic_unit]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_IBUF_BUFG]
