# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projekte/Arty/hw/hw.srcs/sources_1/ip/UART_Fifo/UART_Fifo.xci
# IP: The module: 'UART_Fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/UART_Fifo/UART_Fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/UART_Fifo/UART_Fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Projekte/Arty/hw/hw.srcs/sources_1/ip/UART_Fifo/UART_Fifo.xci
# IP: The module: 'UART_Fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/UART_Fifo/UART_Fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/UART_Fifo/UART_Fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
