# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Arty-S7-25-Master.xdc

# XDC: new/Arty-S7-25-Debug.xdc

# IP: ip/UART_Fifo/UART_Fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Fifo || ORIG_REF_NAME==UART_Fifo} -quiet] -quiet
