# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projekte/Arty/hw/hw.srcs/sources_1/ip/DataRam/DataRam.xci
# IP: The module: 'DataRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/DataRam/DataRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataRam'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Projekte/Arty/hw/hw.srcs/sources_1/ip/DataRam/DataRam.xci
# IP: The module: 'DataRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projekte/Arty/hw/hw.gen/sources_1/ip/DataRam/DataRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataRam'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
